package com.jf.dao;

import com.jf.model.JFGroupMark;
import com.jf.model.JFGroupMarkExample;
import com.jf.model.JFGroupMarkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JFGroupMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int countByExample(JFGroupMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int deleteByExample(JFGroupMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(JFGroupMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int insert(JFGroupMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int insertSelective(JFGroupMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    List<JFGroupMark> selectByExample(JFGroupMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    JFGroupMark selectByPrimaryKey(JFGroupMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFGroupMark record, @Param("example") JFGroupMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFGroupMark record, @Param("example") JFGroupMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JFGroupMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groupmark
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JFGroupMark record);
    
    List<JFGroupMark> getGroupMarks(JFGroupMark groupMark);
    
    void delGroupMark(JFGroupMark groupMark);
    
    Integer getGroupMark(JFGroupMark groupMark);
    
    JFGroupMark groupMark(JFGroupMark groupMark);
    
}