package com.jf.dao;

import com.jf.model.JFPercent;
import com.jf.model.JFPercentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JFPercentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int countByExample(JFPercentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int deleteByExample(JFPercentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Double adminPercent);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int insert(JFPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int insertSelective(JFPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    List<JFPercent> selectByExample(JFPercentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFPercent record, @Param("example") JFPercentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table percent
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFPercent record, @Param("example") JFPercentExample example);
    
    void updatePercent(JFPercent percent);
    
    JFPercent getPercent();
    
    
}