package com.jf.dao;

import com.jf.model.JFSpeech;
import com.jf.model.JFSpeechExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JFSpeechMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int countByExample(JFSpeechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int deleteByExample(JFSpeechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String speechId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int insert(JFSpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int insertSelective(JFSpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    List<JFSpeech> selectByExample(JFSpeechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    JFSpeech selectByPrimaryKey(String speechId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFSpeech record, @Param("example") JFSpeechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFSpeech record, @Param("example") JFSpeechExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JFSpeech record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JFSpeech record);
    
    JFSpeech getSpeech(@Param("speechId")String speechId, @Param("teaId")String teaId, @Param("stuId")String stuId,@Param("teaTitle")String teaTitle, @Param("speechTitle")String speechTitle);
    
    
    
}