package com.jf.dao;

import com.jf.model.JFStudent;
import com.jf.model.JFStudentExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JFStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int countByExample(JFStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int deleteByExample(JFStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int insert(JFStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int insertSelective(JFStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    List<JFStudent> selectByExample(JFStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    JFStudent selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFStudent record, @Param("example") JFStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFStudent record, @Param("example") JFStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JFStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    
    List<JFStudent> getList();
    
    List<JFStudent> getStudents(@Param("begin")int begin,@Param("end") int end,@Param("stuId")String stuId,@Param("stuName")String stuName,@Param("teaId")String teaId,@Param("groupId")String groupId,@Param("speechId")String speechId,@Param("classNo")int classNo);
    
    int getCount(@Param("stuId")String stuId,@Param("stuName")String stuName,@Param("teaId")String teaId,@Param("groupId")String groupId,@Param("speechId")String speechId,@Param("classNo")int classNo);
    
    JFStudent getStudent(String stu_id);
    
    void updatedel(@Param("groId")String groId);
    
    List<JFStudent> getStudentList(JFStudent student);
    
    JFStudent getStu(JFStudent student);
}