package com.jf.dao;

import com.jf.model.JFTeacher;
import com.jf.model.JFTeacherExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface JFTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int countByExample(JFTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int deleteByExample(JFTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int insert(JFTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int insertSelective(JFTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    List<JFTeacher> selectByExample(JFTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    JFTeacher selectByPrimaryKey(String teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFTeacher record, @Param("example") JFTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFTeacher record, @Param("example") JFTeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JFTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JFTeacher record);
    
    List<JFTeacher> getTeachers(@Param("begin")int begin,@Param("end") int end,@Param("teaId")String teaId,@Param("teaName")String teaName,@Param("groId")String groId,@Param("groType")Integer groType,@Param("speechCount")Integer speechCount);
    
    JFTeacher getTeacher(@Param("teaId")String teaId);
    
    void update(JFTeacher teacher);
    
    int getCount(@Param("teaId")String teaId,@Param("teaName")String teaName,@Param("groId")String groId,@Param("groType")Integer groType,@Param("speechCount")Integer speechCount);
    
    String getTeaId(@Param("teaName")String teaName);
    
    List<JFTeacher> getList();
    
    String getTeaName(@Param("teaId")String teaId);
    
    void updatedel(@Param("groId")String groId);
    
    List<JFTeacher> getTeacherList(@Param("groId")String groId);
    
}