package com.jf.dao;

import com.jf.model.JFTeacherMark;
import com.jf.model.JFTeacherMarkExample;
import com.jf.model.JFTeacherMarkKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JFTeacherMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int countByExample(JFTeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int deleteByExample(JFTeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(JFTeacherMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int insert(JFTeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int insertSelective(JFTeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    List<JFTeacherMark> selectByExample(JFTeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    JFTeacherMark selectByPrimaryKey(JFTeacherMarkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JFTeacherMark record, @Param("example") JFTeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JFTeacherMark record, @Param("example") JFTeacherMarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JFTeacherMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachermark
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JFTeacherMark record);
    
    /**
     * jianfeng
     */
    List<JFTeacherMark> getTeacherMarks(JFTeacherMark teacherMark);
    
    void delTeacherMark(JFTeacherMark teacherMark);
    
    Integer getMark(JFTeacherMark teacherMark);
    
    JFTeacherMark getTeacherMark(JFTeacherMark teacherMark);
    
}