package com.jf.model;

import java.util.ArrayList;
import java.util.List;

public class JFCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public JFCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpeechIdIsNull() {
            addCriterion("speech_id is null");
            return (Criteria) this;
        }

        public Criteria andSpeechIdIsNotNull() {
            addCriterion("speech_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpeechIdEqualTo(String value) {
            addCriterion("speech_id =", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotEqualTo(String value) {
            addCriterion("speech_id <>", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdGreaterThan(String value) {
            addCriterion("speech_id >", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdGreaterThanOrEqualTo(String value) {
            addCriterion("speech_id >=", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLessThan(String value) {
            addCriterion("speech_id <", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLessThanOrEqualTo(String value) {
            addCriterion("speech_id <=", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLike(String value) {
            addCriterion("speech_id like", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotLike(String value) {
            addCriterion("speech_id not like", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdIn(List<String> values) {
            addCriterion("speech_id in", values, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotIn(List<String> values) {
            addCriterion("speech_id not in", values, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdBetween(String value1, String value2) {
            addCriterion("speech_id between", value1, value2, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotBetween(String value1, String value2) {
            addCriterion("speech_id not between", value1, value2, "speechId");
            return (Criteria) this;
        }

        public Criteria andTeaComIsNull() {
            addCriterion("tea_com is null");
            return (Criteria) this;
        }

        public Criteria andTeaComIsNotNull() {
            addCriterion("tea_com is not null");
            return (Criteria) this;
        }

        public Criteria andTeaComEqualTo(String value) {
            addCriterion("tea_com =", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComNotEqualTo(String value) {
            addCriterion("tea_com <>", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComGreaterThan(String value) {
            addCriterion("tea_com >", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComGreaterThanOrEqualTo(String value) {
            addCriterion("tea_com >=", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComLessThan(String value) {
            addCriterion("tea_com <", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComLessThanOrEqualTo(String value) {
            addCriterion("tea_com <=", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComLike(String value) {
            addCriterion("tea_com like", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComNotLike(String value) {
            addCriterion("tea_com not like", value, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComIn(List<String> values) {
            addCriterion("tea_com in", values, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComNotIn(List<String> values) {
            addCriterion("tea_com not in", values, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComBetween(String value1, String value2) {
            addCriterion("tea_com between", value1, value2, "teaCom");
            return (Criteria) this;
        }

        public Criteria andTeaComNotBetween(String value1, String value2) {
            addCriterion("tea_com not between", value1, value2, "teaCom");
            return (Criteria) this;
        }

        public Criteria andGroComIsNull() {
            addCriterion("gro_com is null");
            return (Criteria) this;
        }

        public Criteria andGroComIsNotNull() {
            addCriterion("gro_com is not null");
            return (Criteria) this;
        }

        public Criteria andGroComEqualTo(String value) {
            addCriterion("gro_com =", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComNotEqualTo(String value) {
            addCriterion("gro_com <>", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComGreaterThan(String value) {
            addCriterion("gro_com >", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComGreaterThanOrEqualTo(String value) {
            addCriterion("gro_com >=", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComLessThan(String value) {
            addCriterion("gro_com <", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComLessThanOrEqualTo(String value) {
            addCriterion("gro_com <=", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComLike(String value) {
            addCriterion("gro_com like", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComNotLike(String value) {
            addCriterion("gro_com not like", value, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComIn(List<String> values) {
            addCriterion("gro_com in", values, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComNotIn(List<String> values) {
            addCriterion("gro_com not in", values, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComBetween(String value1, String value2) {
            addCriterion("gro_com between", value1, value2, "groCom");
            return (Criteria) this;
        }

        public Criteria andGroComNotBetween(String value1, String value2) {
            addCriterion("gro_com not between", value1, value2, "groCom");
            return (Criteria) this;
        }

        public Criteria andBack1IsNull() {
            addCriterion("back1 is null");
            return (Criteria) this;
        }

        public Criteria andBack1IsNotNull() {
            addCriterion("back1 is not null");
            return (Criteria) this;
        }

        public Criteria andBack1EqualTo(String value) {
            addCriterion("back1 =", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotEqualTo(String value) {
            addCriterion("back1 <>", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThan(String value) {
            addCriterion("back1 >", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThanOrEqualTo(String value) {
            addCriterion("back1 >=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThan(String value) {
            addCriterion("back1 <", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThanOrEqualTo(String value) {
            addCriterion("back1 <=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Like(String value) {
            addCriterion("back1 like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotLike(String value) {
            addCriterion("back1 not like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1In(List<String> values) {
            addCriterion("back1 in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotIn(List<String> values) {
            addCriterion("back1 not in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Between(String value1, String value2) {
            addCriterion("back1 between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotBetween(String value1, String value2) {
            addCriterion("back1 not between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack2IsNull() {
            addCriterion("back2 is null");
            return (Criteria) this;
        }

        public Criteria andBack2IsNotNull() {
            addCriterion("back2 is not null");
            return (Criteria) this;
        }

        public Criteria andBack2EqualTo(String value) {
            addCriterion("back2 =", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotEqualTo(String value) {
            addCriterion("back2 <>", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThan(String value) {
            addCriterion("back2 >", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThanOrEqualTo(String value) {
            addCriterion("back2 >=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThan(String value) {
            addCriterion("back2 <", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThanOrEqualTo(String value) {
            addCriterion("back2 <=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Like(String value) {
            addCriterion("back2 like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotLike(String value) {
            addCriterion("back2 not like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2In(List<String> values) {
            addCriterion("back2 in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotIn(List<String> values) {
            addCriterion("back2 not in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Between(String value1, String value2) {
            addCriterion("back2 between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotBetween(String value1, String value2) {
            addCriterion("back2 not between", value1, value2, "back2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}