package com.jf.model;

public class JFGroupMark extends JFGroupMarkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_a
     *
     * @mbggenerated
     */
    private Integer groA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_b
     *
     * @mbggenerated
     */
    private Integer groB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_c
     *
     * @mbggenerated
     */
    private Integer groC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_d
     *
     * @mbggenerated
     */
    private Integer groD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_e
     *
     * @mbggenerated
     */
    private Integer groE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_f
     *
     * @mbggenerated
     */
    private Integer groF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_g
     *
     * @mbggenerated
     */
    private Integer groG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.gro_h
     *
     * @mbggenerated
     */
    private Integer groH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.back9
     *
     * @mbggenerated
     */
    private Integer back9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupmark.back10
     *
     * @mbggenerated
     */
    private Integer back10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_a
     *
     * @return the value of groupmark.gro_a
     *
     * @mbggenerated
     */
    public Integer getGroA() {
        return groA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_a
     *
     * @param groA the value for groupmark.gro_a
     *
     * @mbggenerated
     */
    public void setGroA(Integer groA) {
        this.groA = groA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_b
     *
     * @return the value of groupmark.gro_b
     *
     * @mbggenerated
     */
    public Integer getGroB() {
        return groB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_b
     *
     * @param groB the value for groupmark.gro_b
     *
     * @mbggenerated
     */
    public void setGroB(Integer groB) {
        this.groB = groB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_c
     *
     * @return the value of groupmark.gro_c
     *
     * @mbggenerated
     */
    public Integer getGroC() {
        return groC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_c
     *
     * @param groC the value for groupmark.gro_c
     *
     * @mbggenerated
     */
    public void setGroC(Integer groC) {
        this.groC = groC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_d
     *
     * @return the value of groupmark.gro_d
     *
     * @mbggenerated
     */
    public Integer getGroD() {
        return groD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_d
     *
     * @param groD the value for groupmark.gro_d
     *
     * @mbggenerated
     */
    public void setGroD(Integer groD) {
        this.groD = groD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_e
     *
     * @return the value of groupmark.gro_e
     *
     * @mbggenerated
     */
    public Integer getGroE() {
        return groE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_e
     *
     * @param groE the value for groupmark.gro_e
     *
     * @mbggenerated
     */
    public void setGroE(Integer groE) {
        this.groE = groE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_f
     *
     * @return the value of groupmark.gro_f
     *
     * @mbggenerated
     */
    public Integer getGroF() {
        return groF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_f
     *
     * @param groF the value for groupmark.gro_f
     *
     * @mbggenerated
     */
    public void setGroF(Integer groF) {
        this.groF = groF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_g
     *
     * @return the value of groupmark.gro_g
     *
     * @mbggenerated
     */
    public Integer getGroG() {
        return groG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_g
     *
     * @param groG the value for groupmark.gro_g
     *
     * @mbggenerated
     */
    public void setGroG(Integer groG) {
        this.groG = groG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.gro_h
     *
     * @return the value of groupmark.gro_h
     *
     * @mbggenerated
     */
    public Integer getGroH() {
        return groH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.gro_h
     *
     * @param groH the value for groupmark.gro_h
     *
     * @mbggenerated
     */
    public void setGroH(Integer groH) {
        this.groH = groH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.back9
     *
     * @return the value of groupmark.back9
     *
     * @mbggenerated
     */
    public Integer getBack9() {
        return back9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.back9
     *
     * @param back9 the value for groupmark.back9
     *
     * @mbggenerated
     */
    public void setBack9(Integer back9) {
        this.back9 = back9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupmark.back10
     *
     * @return the value of groupmark.back10
     *
     * @mbggenerated
     */
    public Integer getBack10() {
        return back10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupmark.back10
     *
     * @param back10 the value for groupmark.back10
     *
     * @mbggenerated
     */
    public void setBack10(Integer back10) {
        this.back10 = back10;
    }
    
    /*
     * jianfeng
     * 查指导总分
     */
    
    private String teaName;
    
    /**
	 * @return the score
	 */
	public int getScore() {
		return score;
	}

	/**
	 * @param score the score to set
	 */
	public void setScore(int score) {
		this.score = score;
	}

	/**
	 * @return the teaName
	 */
	public String getTeaName() {
		return teaName;
	}

	/**
	 * @param teaName the teaName to set
	 */
	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	/**
	 * @return the student
	 */
	public JFStudent getStudent() {
		return student;
	}

	/**
	 * @param student the student to set
	 */
	public void setStudent(JFStudent student) {
		this.student = student;
	}

	//jianfeng
	private int score;
    
	private JFStudent student;
	

	
	
}
