package com.jf.model;

import java.util.Date;
public class JFGroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.gro_id
     *
     * @mbggenerated
     */
    private String groId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.gro_address
     *
     * @mbggenerated
     */
    private String groAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.gro_time
     *
     * @mbggenerated
     */
    private Date groTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.gro_id
     *
     * @return the value of groupinfo.gro_id
     *
     * @mbggenerated
     */
    public String getGroId() {
        return groId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.gro_id
     *
     * @param groId the value for groupinfo.gro_id
     *
     * @mbggenerated
     */
    public void setGroId(String groId) {
        this.groId = groId == null ? null : groId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.gro_address
     *
     * @return the value of groupinfo.gro_address
     *
     * @mbggenerated
     */
    public String getGroAddress() {
        return groAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.gro_address
     *
     * @param groAddress the value for groupinfo.gro_address
     *
     * @mbggenerated
     */
    public void setGroAddress(String groAddress) {
        this.groAddress = groAddress == null ? null : groAddress.trim();
    }

	/**
	 * @return the groTime
	 */
	public Date getGroTime() {
		return groTime;
	}

	/**
	 * @param groTime the groTime to set
	 */
	public void setGroTime(Date groTime) {
		this.groTime = groTime;
	}


  
}