package com.jf.model;

public class JFPercent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column percent.admin_percent
     *
     * @mbggenerated
     */
    private Double adminPercent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column percent.admin_percent
     *
     * @return the value of percent.admin_percent
     *
     * @mbggenerated
     */
    public Double getAdminPercent() {
        return adminPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column percent.admin_percent
     *
     * @param adminPercent the value for percent.admin_percent
     *
     * @mbggenerated
     */
    public void setAdminPercent(Double adminPercent) {
        this.adminPercent = adminPercent;
    }
}