package com.jf.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JFSpeechExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table speech
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table speech
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table speech
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public JFSpeechExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table speech
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table speech
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpeechIdIsNull() {
            addCriterion("speech_id is null");
            return (Criteria) this;
        }

        public Criteria andSpeechIdIsNotNull() {
            addCriterion("speech_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpeechIdEqualTo(String value) {
            addCriterion("speech_id =", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotEqualTo(String value) {
            addCriterion("speech_id <>", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdGreaterThan(String value) {
            addCriterion("speech_id >", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdGreaterThanOrEqualTo(String value) {
            addCriterion("speech_id >=", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLessThan(String value) {
            addCriterion("speech_id <", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLessThanOrEqualTo(String value) {
            addCriterion("speech_id <=", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdLike(String value) {
            addCriterion("speech_id like", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotLike(String value) {
            addCriterion("speech_id not like", value, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdIn(List<String> values) {
            addCriterion("speech_id in", values, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotIn(List<String> values) {
            addCriterion("speech_id not in", values, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdBetween(String value1, String value2) {
            addCriterion("speech_id between", value1, value2, "speechId");
            return (Criteria) this;
        }

        public Criteria andSpeechIdNotBetween(String value1, String value2) {
            addCriterion("speech_id not between", value1, value2, "speechId");
            return (Criteria) this;
        }

        public Criteria andTeaIdIsNull() {
            addCriterion("tea_id is null");
            return (Criteria) this;
        }

        public Criteria andTeaIdIsNotNull() {
            addCriterion("tea_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeaIdEqualTo(String value) {
            addCriterion("tea_id =", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdNotEqualTo(String value) {
            addCriterion("tea_id <>", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdGreaterThan(String value) {
            addCriterion("tea_id >", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdGreaterThanOrEqualTo(String value) {
            addCriterion("tea_id >=", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdLessThan(String value) {
            addCriterion("tea_id <", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdLessThanOrEqualTo(String value) {
            addCriterion("tea_id <=", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdLike(String value) {
            addCriterion("tea_id like", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdNotLike(String value) {
            addCriterion("tea_id not like", value, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdIn(List<String> values) {
            addCriterion("tea_id in", values, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdNotIn(List<String> values) {
            addCriterion("tea_id not in", values, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdBetween(String value1, String value2) {
            addCriterion("tea_id between", value1, value2, "teaId");
            return (Criteria) this;
        }

        public Criteria andTeaIdNotBetween(String value1, String value2) {
            addCriterion("tea_id not between", value1, value2, "teaId");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(String value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(String value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(String value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(String value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(String value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(String value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLike(String value) {
            addCriterion("stu_id like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotLike(String value) {
            addCriterion("stu_id not like", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<String> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<String> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(String value1, String value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(String value1, String value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andTeaTitleIsNull() {
            addCriterion("tea_title is null");
            return (Criteria) this;
        }

        public Criteria andTeaTitleIsNotNull() {
            addCriterion("tea_title is not null");
            return (Criteria) this;
        }

        public Criteria andTeaTitleEqualTo(String value) {
            addCriterion("tea_title =", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleNotEqualTo(String value) {
            addCriterion("tea_title <>", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleGreaterThan(String value) {
            addCriterion("tea_title >", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleGreaterThanOrEqualTo(String value) {
            addCriterion("tea_title >=", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleLessThan(String value) {
            addCriterion("tea_title <", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleLessThanOrEqualTo(String value) {
            addCriterion("tea_title <=", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleLike(String value) {
            addCriterion("tea_title like", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleNotLike(String value) {
            addCriterion("tea_title not like", value, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleIn(List<String> values) {
            addCriterion("tea_title in", values, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleNotIn(List<String> values) {
            addCriterion("tea_title not in", values, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleBetween(String value1, String value2) {
            addCriterion("tea_title between", value1, value2, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andTeaTitleNotBetween(String value1, String value2) {
            addCriterion("tea_title not between", value1, value2, "teaTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleIsNull() {
            addCriterion("speech_title is null");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleIsNotNull() {
            addCriterion("speech_title is not null");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleEqualTo(String value) {
            addCriterion("speech_title =", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleNotEqualTo(String value) {
            addCriterion("speech_title <>", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleGreaterThan(String value) {
            addCriterion("speech_title >", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleGreaterThanOrEqualTo(String value) {
            addCriterion("speech_title >=", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleLessThan(String value) {
            addCriterion("speech_title <", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleLessThanOrEqualTo(String value) {
            addCriterion("speech_title <=", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleLike(String value) {
            addCriterion("speech_title like", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleNotLike(String value) {
            addCriterion("speech_title not like", value, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleIn(List<String> values) {
            addCriterion("speech_title in", values, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleNotIn(List<String> values) {
            addCriterion("speech_title not in", values, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleBetween(String value1, String value2) {
            addCriterion("speech_title between", value1, value2, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andSpeechTitleNotBetween(String value1, String value2) {
            addCriterion("speech_title not between", value1, value2, "speechTitle");
            return (Criteria) this;
        }

        public Criteria andUpTimeIsNull() {
            addCriterion("up_time is null");
            return (Criteria) this;
        }

        public Criteria andUpTimeIsNotNull() {
            addCriterion("up_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpTimeEqualTo(Date value) {
            addCriterion("up_time =", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotEqualTo(Date value) {
            addCriterion("up_time <>", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeGreaterThan(Date value) {
            addCriterion("up_time >", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("up_time >=", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeLessThan(Date value) {
            addCriterion("up_time <", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeLessThanOrEqualTo(Date value) {
            addCriterion("up_time <=", value, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeIn(List<Date> values) {
            addCriterion("up_time in", values, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotIn(List<Date> values) {
            addCriterion("up_time not in", values, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeBetween(Date value1, Date value2) {
            addCriterion("up_time between", value1, value2, "upTime");
            return (Criteria) this;
        }

        public Criteria andUpTimeNotBetween(Date value1, Date value2) {
            addCriterion("up_time not between", value1, value2, "upTime");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressIsNull() {
            addCriterion("speech_address is null");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressIsNotNull() {
            addCriterion("speech_address is not null");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressEqualTo(String value) {
            addCriterion("speech_address =", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressNotEqualTo(String value) {
            addCriterion("speech_address <>", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressGreaterThan(String value) {
            addCriterion("speech_address >", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressGreaterThanOrEqualTo(String value) {
            addCriterion("speech_address >=", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressLessThan(String value) {
            addCriterion("speech_address <", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressLessThanOrEqualTo(String value) {
            addCriterion("speech_address <=", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressLike(String value) {
            addCriterion("speech_address like", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressNotLike(String value) {
            addCriterion("speech_address not like", value, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressIn(List<String> values) {
            addCriterion("speech_address in", values, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressNotIn(List<String> values) {
            addCriterion("speech_address not in", values, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressBetween(String value1, String value2) {
            addCriterion("speech_address between", value1, value2, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andSpeechAddressNotBetween(String value1, String value2) {
            addCriterion("speech_address not between", value1, value2, "speechAddress");
            return (Criteria) this;
        }

        public Criteria andBack1IsNull() {
            addCriterion("back1 is null");
            return (Criteria) this;
        }

        public Criteria andBack1IsNotNull() {
            addCriterion("back1 is not null");
            return (Criteria) this;
        }

        public Criteria andBack1EqualTo(String value) {
            addCriterion("back1 =", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotEqualTo(String value) {
            addCriterion("back1 <>", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThan(String value) {
            addCriterion("back1 >", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThanOrEqualTo(String value) {
            addCriterion("back1 >=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThan(String value) {
            addCriterion("back1 <", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThanOrEqualTo(String value) {
            addCriterion("back1 <=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Like(String value) {
            addCriterion("back1 like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotLike(String value) {
            addCriterion("back1 not like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1In(List<String> values) {
            addCriterion("back1 in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotIn(List<String> values) {
            addCriterion("back1 not in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Between(String value1, String value2) {
            addCriterion("back1 between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotBetween(String value1, String value2) {
            addCriterion("back1 not between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack2IsNull() {
            addCriterion("back2 is null");
            return (Criteria) this;
        }

        public Criteria andBack2IsNotNull() {
            addCriterion("back2 is not null");
            return (Criteria) this;
        }

        public Criteria andBack2EqualTo(String value) {
            addCriterion("back2 =", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotEqualTo(String value) {
            addCriterion("back2 <>", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThan(String value) {
            addCriterion("back2 >", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThanOrEqualTo(String value) {
            addCriterion("back2 >=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThan(String value) {
            addCriterion("back2 <", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThanOrEqualTo(String value) {
            addCriterion("back2 <=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Like(String value) {
            addCriterion("back2 like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotLike(String value) {
            addCriterion("back2 not like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2In(List<String> values) {
            addCriterion("back2 in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotIn(List<String> values) {
            addCriterion("back2 not in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Between(String value1, String value2) {
            addCriterion("back2 between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotBetween(String value1, String value2) {
            addCriterion("back2 not between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack3IsNull() {
            addCriterion("back3 is null");
            return (Criteria) this;
        }

        public Criteria andBack3IsNotNull() {
            addCriterion("back3 is not null");
            return (Criteria) this;
        }

        public Criteria andBack3EqualTo(String value) {
            addCriterion("back3 =", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotEqualTo(String value) {
            addCriterion("back3 <>", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThan(String value) {
            addCriterion("back3 >", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThanOrEqualTo(String value) {
            addCriterion("back3 >=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThan(String value) {
            addCriterion("back3 <", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThanOrEqualTo(String value) {
            addCriterion("back3 <=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Like(String value) {
            addCriterion("back3 like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotLike(String value) {
            addCriterion("back3 not like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3In(List<String> values) {
            addCriterion("back3 in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotIn(List<String> values) {
            addCriterion("back3 not in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Between(String value1, String value2) {
            addCriterion("back3 between", value1, value2, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotBetween(String value1, String value2) {
            addCriterion("back3 not between", value1, value2, "back3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table speech
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table speech
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}