package com.jf.model;

import java.util.Date;

public class JFSpeech {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.speech_id
     *
     * @mbggenerated
     */
    private String speechId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.tea_title
     *
     * @mbggenerated
     */
    private String teaTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.speech_title
     *
     * @mbggenerated
     */
    private String speechTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.up_time
     *
     * @mbggenerated
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.speech_address
     *
     * @mbggenerated
     */
    private String speechAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.back1
     *
     * @mbggenerated
     */
    private String back1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.back2
     *
     * @mbggenerated
     */
    private String back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speech.back3
     *
     * @mbggenerated
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.speech_id
     *
     * @return the value of speech.speech_id
     *
     * @mbggenerated
     */
    public String getSpeechId() {
        return speechId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.speech_id
     *
     * @param speechId the value for speech.speech_id
     *
     * @mbggenerated
     */
    public void setSpeechId(String speechId) {
        this.speechId = speechId == null ? null : speechId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.tea_id
     *
     * @return the value of speech.tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.tea_id
     *
     * @param teaId the value for speech.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.stu_id
     *
     * @return the value of speech.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.stu_id
     *
     * @param stuId the value for speech.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.tea_title
     *
     * @return the value of speech.tea_title
     *
     * @mbggenerated
     */
    public String getTeaTitle() {
        return teaTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.tea_title
     *
     * @param teaTitle the value for speech.tea_title
     *
     * @mbggenerated
     */
    public void setTeaTitle(String teaTitle) {
        this.teaTitle = teaTitle == null ? null : teaTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.speech_title
     *
     * @return the value of speech.speech_title
     *
     * @mbggenerated
     */
    public String getSpeechTitle() {
        return speechTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.speech_title
     *
     * @param speechTitle the value for speech.speech_title
     *
     * @mbggenerated
     */
    public void setSpeechTitle(String speechTitle) {
        this.speechTitle = speechTitle == null ? null : speechTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.up_time
     *
     * @return the value of speech.up_time
     *
     * @mbggenerated
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.up_time
     *
     * @param upTime the value for speech.up_time
     *
     * @mbggenerated
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.speech_address
     *
     * @return the value of speech.speech_address
     *
     * @mbggenerated
     */
    public String getSpeechAddress() {
        return speechAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.speech_address
     *
     * @param speechAddress the value for speech.speech_address
     *
     * @mbggenerated
     */
    public void setSpeechAddress(String speechAddress) {
        this.speechAddress = speechAddress == null ? null : speechAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.back1
     *
     * @return the value of speech.back1
     *
     * @mbggenerated
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.back1
     *
     * @param back1 the value for speech.back1
     *
     * @mbggenerated
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.back2
     *
     * @return the value of speech.back2
     *
     * @mbggenerated
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.back2
     *
     * @param back2 the value for speech.back2
     *
     * @mbggenerated
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speech.back3
     *
     * @return the value of speech.back3
     *
     * @mbggenerated
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speech.back3
     *
     * @param back3 the value for speech.back3
     *
     * @mbggenerated
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}