package com.jf.model;

public class JFStudent {
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.speech_id
     *
     * @mbggenerated
     */
    private String speechId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classNo
     *
     * @mbggenerated
     */
    private int classNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.back2
     *
     * @mbggenerated
     */
    private String back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.back3
     *
     * @mbggenerated
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tea_id
     *
     * @return the value of student.tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tea_id
     *
     * @param teaId the value for student.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.group_id
     *
     * @return the value of student.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.group_id
     *
     * @param groupId the value for student.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.speech_id
     *
     * @return the value of student.speech_id
     *
     * @mbggenerated
     */
    public String getSpeechId() {
        return speechId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.speech_id
     *
     * @param speechId the value for student.speech_id
     *
     * @mbggenerated
     */
    public void setSpeechId(String speechId) {
        this.speechId = speechId == null ? null : speechId.trim();
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.back2
     *
     * @return the value of student.back2
     *
     * @mbggenerated
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.back2
     *
     * @param back2 the value for student.back2
     *
     * @mbggenerated
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.back3
     *
     * @return the value of student.back3
     *
     * @mbggenerated
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.back3
     *
     * @param back3 the value for student.back3
     *
     * @mbggenerated
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }

	/**
	 * jianfeng add model teaName
	 */
	private String teaName;
	 
	private int score;
	
	private String speechTitle;
	
	private String teaCom;
	
	private String groCom;
	
    public String getTeaName() {
		return teaName;
	}

	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	public int getScore() {
		return score;
	}

	/**
	 * @param score the score to set
	 */
	public void setScore(int score) {
		this.score = score;
	}

	/**
	 * @return the speechTitle
	 */
	public String getSpeechTitle() {
		return speechTitle;
	}

	/**
	 * @param speechTitle the speechTitle to set
	 */
	public void setSpeechTitle(String speechTitle) {
		this.speechTitle = speechTitle;
	}

	/**
	 * @return the teaCom
	 */
	public String getTeaCom() {
		return teaCom;
	}

	/**
	 * @param teaCom the teaCom to set
	 */
	public void setTeaCom(String teaCom) {
		this.teaCom = teaCom;
	}

	/**
	 * @return the groCom
	 */
	public String getGroCom() {
		return groCom;
	}

	/**
	 * @param groCom the groCom to set
	 */
	public void setGroCom(String groCom) {
		this.groCom = groCom;
	}

	/**
	 * @return the classNo
	 */
	public int getClassNo() {
		return classNo;
	}

	/**
	 * @param classNo the classNo to set
	 */
	public void setClassNo(int classNo) {
		this.classNo = classNo;
	}
	
	/**
	 * @return the className
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * @param className the className to set
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	private String className;

}