package com.jf.model;

public class JFTeacherMarkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.stu_id
     *
     * @return the value of teachermark.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.stu_id
     *
     * @param stuId the value for teachermark.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_id
     *
     * @return the value of teachermark.tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_id
     *
     * @param teaId the value for teachermark.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }
}