package com.jf.model;

public class JFTeacherMark extends JFTeacherMarkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_a
     *
     * @mbggenerated
     */
    private Integer teaA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_b
     *
     * @mbggenerated
     */
    private Integer teaB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_c
     *
     * @mbggenerated
     */
    private Integer teaC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_d
     *
     * @mbggenerated
     */
    private Integer teaD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_e
     *
     * @mbggenerated
     */
    private Integer teaE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_f
     *
     * @mbggenerated
     */
    private Integer teaF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_g
     *
     * @mbggenerated
     */
    private Integer teaG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.tea_h
     *
     * @mbggenerated
     */
    private Integer teaH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.back9
     *
     * @mbggenerated
     */
    private Integer back9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachermark.back10
     *
     * @mbggenerated
     */
    private Integer back10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_a
     *
     * @return the value of teachermark.tea_a
     *
     * @mbggenerated
     */
    public Integer getTeaA() {
        return teaA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_a
     *
     * @param teaA the value for teachermark.tea_a
     *
     * @mbggenerated
     */
    public void setTeaA(Integer teaA) {
        this.teaA = teaA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_b
     *
     * @return the value of teachermark.tea_b
     *
     * @mbggenerated
     */
    public Integer getTeaB() {
        return teaB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_b
     *
     * @param teaB the value for teachermark.tea_b
     *
     * @mbggenerated
     */
    public void setTeaB(Integer teaB) {
        this.teaB = teaB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_c
     *
     * @return the value of teachermark.tea_c
     *
     * @mbggenerated
     */
    public Integer getTeaC() {
        return teaC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_c
     *
     * @param teaC the value for teachermark.tea_c
     *
     * @mbggenerated
     */
    public void setTeaC(Integer teaC) {
        this.teaC = teaC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_d
     *
     * @return the value of teachermark.tea_d
     *
     * @mbggenerated
     */
    public Integer getTeaD() {
        return teaD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_d
     *
     * @param teaD the value for teachermark.tea_d
     *
     * @mbggenerated
     */
    public void setTeaD(Integer teaD) {
        this.teaD = teaD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_e
     *
     * @return the value of teachermark.tea_e
     *
     * @mbggenerated
     */
    public Integer getTeaE() {
        return teaE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_e
     *
     * @param teaE the value for teachermark.tea_e
     *
     * @mbggenerated
     */
    public void setTeaE(Integer teaE) {
        this.teaE = teaE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_f
     *
     * @return the value of teachermark.tea_f
     *
     * @mbggenerated
     */
    public Integer getTeaF() {
        return teaF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_f
     *
     * @param teaF the value for teachermark.tea_f
     *
     * @mbggenerated
     */
    public void setTeaF(Integer teaF) {
        this.teaF = teaF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.tea_g
     *
     * @return the value of teachermark.tea_g
     *
     * @mbggenerated
     */
    public Integer getTeaG() {
        return teaG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.tea_g
     *
     * @param teaG the value for teachermark.tea_g
     *
     * @mbggenerated
     */
    public void setTeaG(Integer teaG) {
        this.teaG = teaG;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.back9
     *
     * @return the value of teachermark.back9
     *
     * @mbggenerated
     */
    public Integer getBack9() {
        return back9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.back9
     *
     * @param back9 the value for teachermark.back9
     *
     * @mbggenerated
     */
    public void setBack9(Integer back9) {
        this.back9 = back9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachermark.back10
     *
     * @return the value of teachermark.back10
     *
     * @mbggenerated
     */
    public Integer getBack10() {
        return back10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachermark.back10
     *
     * @param back10 the value for teachermark.back10
     *
     * @mbggenerated
     */
    public void setBack10(Integer back10) {
        this.back10 = back10;
    }
    
    /**
     * jianfeng
     * score计算总分
     */
    
    private int score;
    
    
    /**
	 * @return the score
	 */
	public int getScore() {
		return score;
	}

	/**
	 * @param score the score to set
	 */
	public void setScore(int score) {
		this.score = score;
	}

	/**
	 * @return the teaH
	 */
	public Integer getTeaH() {
		return teaH;
	}

	/**
	 * @param teaH the teaH to set
	 */
	public void setTeaH(Integer teaH) {
		this.teaH = teaH;
	}
	
	/**
	 * @return the student
	 */
	public JFStudent getStudent() {
		return student;
	}

	/**
	 * @param student the student to set
	 */
	public void setStudent(JFStudent student) {
		this.student = student;
	}

	/**
	 * @return the teaName
	 */
	public String getTeaName() {
		return teaName;
	}

	/**
	 * @param teaName the teaName to set
	 */
	public void setTeaName(String teaName) {
		this.teaName = teaName;
	}

	private JFStudent student;
	
	private String teaName;
	
	
	
    
}