package com.jf.model;

public class JFTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tea_name
     *
     * @mbggenerated
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gro_id
     *
     * @mbggenerated
     */
    private String groId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gro_type
     *
     * @mbggenerated
     */
    private Integer groType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.speech_count
     *
     * @mbggenerated
     */
    private Integer speechCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.back1
     *
     * @mbggenerated
     */
    private String back1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.back2
     *
     * @mbggenerated
     */
    private String back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.back3
     *
     * @mbggenerated
     */
    private String back3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.back4
     *
     * @mbggenerated
     */
    private String back4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_id
     *
     * @return the value of teacher.tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_id
     *
     * @param teaId the value for teacher.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tea_name
     *
     * @return the value of teacher.tea_name
     *
     * @mbggenerated
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tea_name
     *
     * @param teaName the value for teacher.tea_name
     *
     * @mbggenerated
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gro_id
     *
     * @return the value of teacher.gro_id
     *
     * @mbggenerated
     */
    public String getGroId() {
        return groId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gro_id
     *
     * @param groId the value for teacher.gro_id
     *
     * @mbggenerated
     */
    public void setGroId(String groId) {
        this.groId = groId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gro_type
     *
     * @return the value of teacher.gro_type
     *
     * @mbggenerated
     */
    public Integer getGroType() {
        return groType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gro_type
     *
     * @param groType the value for teacher.gro_type
     *
     * @mbggenerated
     */
    public void setGroType(Integer groType) {
        this.groType = groType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.speech_count
     *
     * @return the value of teacher.speech_count
     *
     * @mbggenerated
     */
    public Integer getSpeechCount() {
        return speechCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.speech_count
     *
     * @param speechCount the value for teacher.speech_count
     *
     * @mbggenerated
     */
    public void setSpeechCount(Integer speechCount) {
        this.speechCount = speechCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.back1
     *
     * @return the value of teacher.back1
     *
     * @mbggenerated
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.back1
     *
     * @param back1 the value for teacher.back1
     *
     * @mbggenerated
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.back2
     *
     * @return the value of teacher.back2
     *
     * @mbggenerated
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.back2
     *
     * @param back2 the value for teacher.back2
     *
     * @mbggenerated
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.back3
     *
     * @return the value of teacher.back3
     *
     * @mbggenerated
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.back3
     *
     * @param back3 the value for teacher.back3
     *
     * @mbggenerated
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.back4
     *
     * @return the value of teacher.back4
     *
     * @mbggenerated
     */
    public String getBack4() {
        return back4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.back4
     *
     * @param back4 the value for teacher.back4
     *
     * @mbggenerated
     */
    public void setBack4(String back4) {
        this.back4 = back4 == null ? null : back4.trim();
    }
}